### ISSUE TITLE
why the tool open the /etc/passwd

### ISSUE THREAD

**Issue by k3mlol** [QaQAdrian/monitor#1]
virustotal scan result:https://www.virustotal.com/gui/file/bfb013cc6e0e4ec3e8ba6f9b69ed94af8aa14af21bb223ea0f08306544259da6/behavior/VirusTotal%20Box%20of%20Apples

as you can see the tool open the **/etc/paswd** and **/etc/master.passwd**,why the tool need to read 2 file?

**Comment by blabla-yy** [comment]
These two files are not actively read by the project. I try to upload several apps to this websit, include Apple's app. All of these apps read them too. 

These files has lots of basic information, such as user's name, user's home directory and user's shell env. And it is public for reading. You can open "file:///etc/passwd" on chrome directly. The passwd file is generated from the master.passwd file. And master.passwd is encrypted.

So don't worry. It seems that every application needs to read these two files. And it is automatically called by the system.

**Comment by k3mlol** [comment]
thx your detailed reply
